// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mxgate_service.proto

package cn.ymatrix.api;

/**
 * Protobuf type {@code api.ColumnMeta}
 */
public final class ColumnMeta extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.ColumnMeta)
    ColumnMetaOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ColumnMeta.newBuilder() to construct.
  private ColumnMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ColumnMeta() {
    type_ = "";
    name_ = "";
    default_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ColumnMeta();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ColumnMeta(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {

            num_ = input.readInt32();
            break;
          }
          case 32: {

            isNotNull_ = input.readBool();
            break;
          }
          case 40: {

            isSetDefault_ = input.readBool();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            default_ = s;
            break;
          }
          case 56: {

            isSerial_ = input.readBool();
            break;
          }
          case 64: {

            isExcluded_ = input.readBool();
            break;
          }
          case 72: {

            isUpsertKey_ = input.readBool();
            break;
          }
          case 80: {

            isDeduplicateKey_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.ymatrix.api.MxGateService.internal_static_api_ColumnMeta_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.ymatrix.api.MxGateService.internal_static_api_ColumnMeta_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.ymatrix.api.ColumnMeta.class, cn.ymatrix.api.ColumnMeta.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object type_;
  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUM_FIELD_NUMBER = 3;
  private int num_;
  /**
   * <code>int32 num = 3;</code>
   * @return The num.
   */
  @java.lang.Override
  public int getNum() {
    return num_;
  }

  public static final int IS_NOT_NULL_FIELD_NUMBER = 4;
  private boolean isNotNull_;
  /**
   * <code>bool is_not_null = 4;</code>
   * @return The isNotNull.
   */
  @java.lang.Override
  public boolean getIsNotNull() {
    return isNotNull_;
  }

  public static final int IS_SET_DEFAULT_FIELD_NUMBER = 5;
  private boolean isSetDefault_;
  /**
   * <code>bool is_set_default = 5;</code>
   * @return The isSetDefault.
   */
  @java.lang.Override
  public boolean getIsSetDefault() {
    return isSetDefault_;
  }

  public static final int DEFAULT_FIELD_NUMBER = 6;
  private volatile java.lang.Object default_;
  /**
   * <code>string default = 6;</code>
   * @return The default.
   */
  @java.lang.Override
  public java.lang.String getDefault() {
    java.lang.Object ref = default_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      default_ = s;
      return s;
    }
  }
  /**
   * <code>string default = 6;</code>
   * @return The bytes for default.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDefaultBytes() {
    java.lang.Object ref = default_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      default_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_SERIAL_FIELD_NUMBER = 7;
  private boolean isSerial_;
  /**
   * <code>bool is_serial = 7;</code>
   * @return The isSerial.
   */
  @java.lang.Override
  public boolean getIsSerial() {
    return isSerial_;
  }

  public static final int IS_EXCLUDED_FIELD_NUMBER = 8;
  private boolean isExcluded_;
  /**
   * <code>bool is_excluded = 8;</code>
   * @return The isExcluded.
   */
  @java.lang.Override
  public boolean getIsExcluded() {
    return isExcluded_;
  }

  /**
   * This column is upsert key.
   */
  public static final int IS_UPSERT_KEY_FIELD_NUMBER = 9;
  private boolean isUpsertKey_;
  /**
   * <code>bool is_upsert_key = 9;</code>
   * @return The isUpsertKey.
   */
  @java.lang.Override
  public boolean getIsUpsertKey() {
    return isUpsertKey_;
  }

  public static final int IS_DEDUPLICATE_KEY_FIELD_NUMBER = 10;
  private boolean isDeduplicateKey_;
  /**
   * <code>bool is_deduplicate_key = 10;</code>
   * @return The isDeduplicateKey.
   */
  @java.lang.Override
  public boolean getIsDeduplicateKey() {
    return isDeduplicateKey_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (num_ != 0) {
      output.writeInt32(3, num_);
    }
    if (isNotNull_ != false) {
      output.writeBool(4, isNotNull_);
    }
    if (isSetDefault_ != false) {
      output.writeBool(5, isSetDefault_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(default_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, default_);
    }
    if (isSerial_ != false) {
      output.writeBool(7, isSerial_);
    }
    if (isExcluded_ != false) {
      output.writeBool(8, isExcluded_);
    }
    if (isUpsertKey_ != false) {
      output.writeBool(9, isUpsertKey_);
    }
    if (isDeduplicateKey_ != false) {
      output.writeBool(10, isDeduplicateKey_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (num_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, num_);
    }
    if (isNotNull_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isNotNull_);
    }
    if (isSetDefault_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isSetDefault_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(default_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, default_);
    }
    if (isSerial_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, isSerial_);
    }
    if (isExcluded_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, isExcluded_);
    }
    if (isUpsertKey_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, isUpsertKey_);
    }
    if (isDeduplicateKey_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, isDeduplicateKey_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.ymatrix.api.ColumnMeta)) {
      return super.equals(obj);
    }
    cn.ymatrix.api.ColumnMeta other = (cn.ymatrix.api.ColumnMeta) obj;

    if (!getType()
        .equals(other.getType())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (getNum()
        != other.getNum()) return false;
    if (getIsNotNull()
        != other.getIsNotNull()) return false;
    if (getIsSetDefault()
        != other.getIsSetDefault()) return false;
    if (!getDefault()
        .equals(other.getDefault())) return false;
    if (getIsSerial()
        != other.getIsSerial()) return false;
    if (getIsExcluded()
        != other.getIsExcluded()) return false;
    if (getIsUpsertKey()
        != other.getIsUpsertKey()) return false;
    if (getIsDeduplicateKey()
        != other.getIsDeduplicateKey()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + NUM_FIELD_NUMBER;
    hash = (53 * hash) + getNum();
    hash = (37 * hash) + IS_NOT_NULL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsNotNull());
    hash = (37 * hash) + IS_SET_DEFAULT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSetDefault());
    hash = (37 * hash) + DEFAULT_FIELD_NUMBER;
    hash = (53 * hash) + getDefault().hashCode();
    hash = (37 * hash) + IS_SERIAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSerial());
    hash = (37 * hash) + IS_EXCLUDED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsExcluded());
    hash = (37 * hash) + IS_UPSERT_KEY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsUpsertKey());
    hash = (37 * hash) + IS_DEDUPLICATE_KEY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsDeduplicateKey());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.ymatrix.api.ColumnMeta parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ymatrix.api.ColumnMeta parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ymatrix.api.ColumnMeta parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ymatrix.api.ColumnMeta parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ymatrix.api.ColumnMeta parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ymatrix.api.ColumnMeta parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ymatrix.api.ColumnMeta parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ymatrix.api.ColumnMeta parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ymatrix.api.ColumnMeta parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.ymatrix.api.ColumnMeta parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ymatrix.api.ColumnMeta parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ymatrix.api.ColumnMeta parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.ymatrix.api.ColumnMeta prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.ColumnMeta}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.ColumnMeta)
      cn.ymatrix.api.ColumnMetaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ymatrix.api.MxGateService.internal_static_api_ColumnMeta_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ymatrix.api.MxGateService.internal_static_api_ColumnMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ymatrix.api.ColumnMeta.class, cn.ymatrix.api.ColumnMeta.Builder.class);
    }

    // Construct using cn.ymatrix.api.ColumnMeta.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = "";

      name_ = "";

      num_ = 0;

      isNotNull_ = false;

      isSetDefault_ = false;

      default_ = "";

      isSerial_ = false;

      isExcluded_ = false;

      isUpsertKey_ = false;

      isDeduplicateKey_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.ymatrix.api.MxGateService.internal_static_api_ColumnMeta_descriptor;
    }

    @java.lang.Override
    public cn.ymatrix.api.ColumnMeta getDefaultInstanceForType() {
      return cn.ymatrix.api.ColumnMeta.getDefaultInstance();
    }

    @java.lang.Override
    public cn.ymatrix.api.ColumnMeta build() {
      cn.ymatrix.api.ColumnMeta result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.ymatrix.api.ColumnMeta buildPartial() {
      cn.ymatrix.api.ColumnMeta result = new cn.ymatrix.api.ColumnMeta(this);
      result.type_ = type_;
      result.name_ = name_;
      result.num_ = num_;
      result.isNotNull_ = isNotNull_;
      result.isSetDefault_ = isSetDefault_;
      result.default_ = default_;
      result.isSerial_ = isSerial_;
      result.isExcluded_ = isExcluded_;
      result.isUpsertKey_ = isUpsertKey_;
      result.isDeduplicateKey_ = isDeduplicateKey_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.ymatrix.api.ColumnMeta) {
        return mergeFrom((cn.ymatrix.api.ColumnMeta)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.ymatrix.api.ColumnMeta other) {
      if (other == cn.ymatrix.api.ColumnMeta.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getNum() != 0) {
        setNum(other.getNum());
      }
      if (other.getIsNotNull() != false) {
        setIsNotNull(other.getIsNotNull());
      }
      if (other.getIsSetDefault() != false) {
        setIsSetDefault(other.getIsSetDefault());
      }
      if (!other.getDefault().isEmpty()) {
        default_ = other.default_;
        onChanged();
      }
      if (other.getIsSerial() != false) {
        setIsSerial(other.getIsSerial());
      }
      if (other.getIsExcluded() != false) {
        setIsExcluded(other.getIsExcluded());
      }
      if (other.getIsUpsertKey() != false) {
        setIsUpsertKey(other.getIsUpsertKey());
      }
      if (other.getIsDeduplicateKey() != false) {
        setIsDeduplicateKey(other.getIsDeduplicateKey());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.ymatrix.api.ColumnMeta parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.ymatrix.api.ColumnMeta) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>string type = 1;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int num_ ;
    /**
     * <code>int32 num = 3;</code>
     * @return The num.
     */
    @java.lang.Override
    public int getNum() {
      return num_;
    }
    /**
     * <code>int32 num = 3;</code>
     * @param value The num to set.
     * @return This builder for chaining.
     */
    public Builder setNum(int value) {
      
      num_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 num = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNum() {
      
      num_ = 0;
      onChanged();
      return this;
    }

    private boolean isNotNull_ ;
    /**
     * <code>bool is_not_null = 4;</code>
     * @return The isNotNull.
     */
    @java.lang.Override
    public boolean getIsNotNull() {
      return isNotNull_;
    }
    /**
     * <code>bool is_not_null = 4;</code>
     * @param value The isNotNull to set.
     * @return This builder for chaining.
     */
    public Builder setIsNotNull(boolean value) {
      
      isNotNull_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_not_null = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsNotNull() {
      
      isNotNull_ = false;
      onChanged();
      return this;
    }

    private boolean isSetDefault_ ;
    /**
     * <code>bool is_set_default = 5;</code>
     * @return The isSetDefault.
     */
    @java.lang.Override
    public boolean getIsSetDefault() {
      return isSetDefault_;
    }
    /**
     * <code>bool is_set_default = 5;</code>
     * @param value The isSetDefault to set.
     * @return This builder for chaining.
     */
    public Builder setIsSetDefault(boolean value) {
      
      isSetDefault_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_set_default = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSetDefault() {
      
      isSetDefault_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object default_ = "";
    /**
     * <code>string default = 6;</code>
     * @return The default.
     */
    public java.lang.String getDefault() {
      java.lang.Object ref = default_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        default_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string default = 6;</code>
     * @return The bytes for default.
     */
    public com.google.protobuf.ByteString
        getDefaultBytes() {
      java.lang.Object ref = default_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        default_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string default = 6;</code>
     * @param value The default to set.
     * @return This builder for chaining.
     */
    public Builder setDefault(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      default_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string default = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDefault() {
      
      default_ = getDefaultInstance().getDefault();
      onChanged();
      return this;
    }
    /**
     * <code>string default = 6;</code>
     * @param value The bytes for default to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      default_ = value;
      onChanged();
      return this;
    }

    private boolean isSerial_ ;
    /**
     * <code>bool is_serial = 7;</code>
     * @return The isSerial.
     */
    @java.lang.Override
    public boolean getIsSerial() {
      return isSerial_;
    }
    /**
     * <code>bool is_serial = 7;</code>
     * @param value The isSerial to set.
     * @return This builder for chaining.
     */
    public Builder setIsSerial(boolean value) {
      
      isSerial_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_serial = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSerial() {
      
      isSerial_ = false;
      onChanged();
      return this;
    }

    private boolean isExcluded_ ;
    /**
     * <code>bool is_excluded = 8;</code>
     * @return The isExcluded.
     */
    @java.lang.Override
    public boolean getIsExcluded() {
      return isExcluded_;
    }
    /**
     * <code>bool is_excluded = 8;</code>
     * @param value The isExcluded to set.
     * @return This builder for chaining.
     */
    public Builder setIsExcluded(boolean value) {
      
      isExcluded_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_excluded = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsExcluded() {
      
      isExcluded_ = false;
      onChanged();
      return this;
    }

    private boolean isUpsertKey_ ;
    /**
     * <code>bool is_upsert_key = 9;</code>
     * @return The isUpsertKey.
     */
    @java.lang.Override
    public boolean getIsUpsertKey() {
      return isUpsertKey_;
    }
    /**
     * <code>bool is_upsert_key = 9;</code>
     * @param value The isUpsertKey to set.
     * @return This builder for chaining.
     */
    public Builder setIsUpsertKey(boolean value) {
      
      isUpsertKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_upsert_key = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsUpsertKey() {
      
      isUpsertKey_ = false;
      onChanged();
      return this;
    }

    private boolean isDeduplicateKey_ ;
    /**
     * <code>bool is_deduplicate_key = 10;</code>
     * @return The isDeduplicateKey.
     */
    @java.lang.Override
    public boolean getIsDeduplicateKey() {
      return isDeduplicateKey_;
    }
    /**
     * <code>bool is_deduplicate_key = 10;</code>
     * @param value The isDeduplicateKey to set.
     * @return This builder for chaining.
     */
    public Builder setIsDeduplicateKey(boolean value) {
      
      isDeduplicateKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_deduplicate_key = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsDeduplicateKey() {
      
      isDeduplicateKey_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.ColumnMeta)
  }

  // @@protoc_insertion_point(class_scope:api.ColumnMeta)
  private static final cn.ymatrix.api.ColumnMeta DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.ymatrix.api.ColumnMeta();
  }

  public static cn.ymatrix.api.ColumnMeta getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ColumnMeta>
      PARSER = new com.google.protobuf.AbstractParser<ColumnMeta>() {
    @java.lang.Override
    public ColumnMeta parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ColumnMeta(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ColumnMeta> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ColumnMeta> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.ymatrix.api.ColumnMeta getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

