// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mxgate_service.proto

package cn.ymatrix.api;

public interface ColumnMetaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.ColumnMeta)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 num = 3;</code>
   * @return The num.
   */
  int getNum();

  /**
   * <code>bool is_not_null = 4;</code>
   * @return The isNotNull.
   */
  boolean getIsNotNull();

  /**
   * <code>bool is_set_default = 5;</code>
   * @return The isSetDefault.
   */
  boolean getIsSetDefault();

  /**
   * <code>string default = 6;</code>
   * @return The default.
   */
  java.lang.String getDefault();
  /**
   * <code>string default = 6;</code>
   * @return The bytes for default.
   */
  com.google.protobuf.ByteString
      getDefaultBytes();

  /**
   * <code>bool is_serial = 7;</code>
   * @return The isSerial.
   */
  boolean getIsSerial();

  /**
   * <code>bool is_excluded = 8;</code>
   * @return The isExcluded.
   */
  boolean getIsExcluded();

  /**
   * <code>bool is_upsert_key = 9;</code>
   * @return The isUpsertKey.
   */
  boolean getIsUpsertKey();

  /**
   * <code>bool is_deduplicate_key = 10;</code>
   * @return The isDeduplicateKey.
   */
  boolean getIsDeduplicateKey();
}
