// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mxgate_service.proto

package cn.ymatrix.api;

public interface GetJobMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.GetJobMetadata)
    com.google.protobuf.MessageOrBuilder {
}
