// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mxgate_service.proto

package cn.ymatrix.api;

/**
 * Protobuf type {@code api.JobMetadata}
 */
public final class JobMetadata extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.JobMetadata)
    JobMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JobMetadata.newBuilder() to construct.
  private JobMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JobMetadata() {
    schema_ = "";
    table_ = "";
    projection_ = "";
    insertProjection_ = "";
    selectProjection_ = "";
    uniqueKeyClause_ = "";
    delimiter_ = "";
    columns_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JobMetadata();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JobMetadata(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            schema_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            table_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            projection_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            insertProjection_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            selectProjection_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            uniqueKeyClause_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            delimiter_ = s;
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              columns_ = new java.util.ArrayList<cn.ymatrix.api.ColumnMeta>();
              mutable_bitField0_ |= 0x00000001;
            }
            columns_.add(
                input.readMessage(cn.ymatrix.api.ColumnMeta.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        columns_ = java.util.Collections.unmodifiableList(columns_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.ymatrix.api.MxGateService.internal_static_api_JobMetadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.ymatrix.api.MxGateService.internal_static_api_JobMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.ymatrix.api.JobMetadata.class, cn.ymatrix.api.JobMetadata.Builder.class);
  }

  public static final int SCHEMA_FIELD_NUMBER = 1;
  private volatile java.lang.Object schema_;
  /**
   * <code>string schema = 1;</code>
   * @return The schema.
   */
  @java.lang.Override
  public java.lang.String getSchema() {
    java.lang.Object ref = schema_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      schema_ = s;
      return s;
    }
  }
  /**
   * <code>string schema = 1;</code>
   * @return The bytes for schema.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSchemaBytes() {
    java.lang.Object ref = schema_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      schema_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TABLE_FIELD_NUMBER = 2;
  private volatile java.lang.Object table_;
  /**
   * <code>string table = 2;</code>
   * @return The table.
   */
  @java.lang.Override
  public java.lang.String getTable() {
    java.lang.Object ref = table_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      table_ = s;
      return s;
    }
  }
  /**
   * <code>string table = 2;</code>
   * @return The bytes for table.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTableBytes() {
    java.lang.Object ref = table_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      table_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROJECTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object projection_;
  /**
   * <code>string projection = 3;</code>
   * @return The projection.
   */
  @java.lang.Override
  public java.lang.String getProjection() {
    java.lang.Object ref = projection_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      projection_ = s;
      return s;
    }
  }
  /**
   * <code>string projection = 3;</code>
   * @return The bytes for projection.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProjectionBytes() {
    java.lang.Object ref = projection_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      projection_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INSERT_PROJECTION_FIELD_NUMBER = 4;
  private volatile java.lang.Object insertProjection_;
  /**
   * <code>string insert_projection = 4;</code>
   * @return The insertProjection.
   */
  @java.lang.Override
  public java.lang.String getInsertProjection() {
    java.lang.Object ref = insertProjection_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      insertProjection_ = s;
      return s;
    }
  }
  /**
   * <code>string insert_projection = 4;</code>
   * @return The bytes for insertProjection.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInsertProjectionBytes() {
    java.lang.Object ref = insertProjection_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      insertProjection_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SELECT_PROJECTION_FIELD_NUMBER = 5;
  private volatile java.lang.Object selectProjection_;
  /**
   * <code>string select_projection = 5;</code>
   * @return The selectProjection.
   */
  @java.lang.Override
  public java.lang.String getSelectProjection() {
    java.lang.Object ref = selectProjection_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      selectProjection_ = s;
      return s;
    }
  }
  /**
   * <code>string select_projection = 5;</code>
   * @return The bytes for selectProjection.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSelectProjectionBytes() {
    java.lang.Object ref = selectProjection_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      selectProjection_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UNIQUE_KEY_CLAUSE_FIELD_NUMBER = 6;
  private volatile java.lang.Object uniqueKeyClause_;
  /**
   * <code>string unique_key_clause = 6;</code>
   * @return The uniqueKeyClause.
   */
  @java.lang.Override
  public java.lang.String getUniqueKeyClause() {
    java.lang.Object ref = uniqueKeyClause_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uniqueKeyClause_ = s;
      return s;
    }
  }
  /**
   * <code>string unique_key_clause = 6;</code>
   * @return The bytes for uniqueKeyClause.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUniqueKeyClauseBytes() {
    java.lang.Object ref = uniqueKeyClause_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uniqueKeyClause_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DELIMITER_FIELD_NUMBER = 7;
  private volatile java.lang.Object delimiter_;
  /**
   * <code>string delimiter = 7;</code>
   * @return The delimiter.
   */
  @java.lang.Override
  public java.lang.String getDelimiter() {
    java.lang.Object ref = delimiter_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      delimiter_ = s;
      return s;
    }
  }
  /**
   * <code>string delimiter = 7;</code>
   * @return The bytes for delimiter.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDelimiterBytes() {
    java.lang.Object ref = delimiter_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      delimiter_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLUMNS_FIELD_NUMBER = 8;
  private java.util.List<cn.ymatrix.api.ColumnMeta> columns_;
  /**
   * <code>repeated .api.ColumnMeta columns = 8;</code>
   */
  @java.lang.Override
  public java.util.List<cn.ymatrix.api.ColumnMeta> getColumnsList() {
    return columns_;
  }
  /**
   * <code>repeated .api.ColumnMeta columns = 8;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cn.ymatrix.api.ColumnMetaOrBuilder> 
      getColumnsOrBuilderList() {
    return columns_;
  }
  /**
   * <code>repeated .api.ColumnMeta columns = 8;</code>
   */
  @java.lang.Override
  public int getColumnsCount() {
    return columns_.size();
  }
  /**
   * <code>repeated .api.ColumnMeta columns = 8;</code>
   */
  @java.lang.Override
  public cn.ymatrix.api.ColumnMeta getColumns(int index) {
    return columns_.get(index);
  }
  /**
   * <code>repeated .api.ColumnMeta columns = 8;</code>
   */
  @java.lang.Override
  public cn.ymatrix.api.ColumnMetaOrBuilder getColumnsOrBuilder(
      int index) {
    return columns_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schema_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, schema_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(table_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, table_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(projection_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, projection_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(insertProjection_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, insertProjection_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(selectProjection_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, selectProjection_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uniqueKeyClause_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, uniqueKeyClause_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(delimiter_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, delimiter_);
    }
    for (int i = 0; i < columns_.size(); i++) {
      output.writeMessage(8, columns_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schema_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, schema_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(table_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, table_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(projection_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, projection_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(insertProjection_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, insertProjection_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(selectProjection_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, selectProjection_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uniqueKeyClause_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, uniqueKeyClause_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(delimiter_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, delimiter_);
    }
    for (int i = 0; i < columns_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, columns_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.ymatrix.api.JobMetadata)) {
      return super.equals(obj);
    }
    cn.ymatrix.api.JobMetadata other = (cn.ymatrix.api.JobMetadata) obj;

    if (!getSchema()
        .equals(other.getSchema())) return false;
    if (!getTable()
        .equals(other.getTable())) return false;
    if (!getProjection()
        .equals(other.getProjection())) return false;
    if (!getInsertProjection()
        .equals(other.getInsertProjection())) return false;
    if (!getSelectProjection()
        .equals(other.getSelectProjection())) return false;
    if (!getUniqueKeyClause()
        .equals(other.getUniqueKeyClause())) return false;
    if (!getDelimiter()
        .equals(other.getDelimiter())) return false;
    if (!getColumnsList()
        .equals(other.getColumnsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCHEMA_FIELD_NUMBER;
    hash = (53 * hash) + getSchema().hashCode();
    hash = (37 * hash) + TABLE_FIELD_NUMBER;
    hash = (53 * hash) + getTable().hashCode();
    hash = (37 * hash) + PROJECTION_FIELD_NUMBER;
    hash = (53 * hash) + getProjection().hashCode();
    hash = (37 * hash) + INSERT_PROJECTION_FIELD_NUMBER;
    hash = (53 * hash) + getInsertProjection().hashCode();
    hash = (37 * hash) + SELECT_PROJECTION_FIELD_NUMBER;
    hash = (53 * hash) + getSelectProjection().hashCode();
    hash = (37 * hash) + UNIQUE_KEY_CLAUSE_FIELD_NUMBER;
    hash = (53 * hash) + getUniqueKeyClause().hashCode();
    hash = (37 * hash) + DELIMITER_FIELD_NUMBER;
    hash = (53 * hash) + getDelimiter().hashCode();
    if (getColumnsCount() > 0) {
      hash = (37 * hash) + COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getColumnsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.ymatrix.api.JobMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ymatrix.api.JobMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ymatrix.api.JobMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ymatrix.api.JobMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ymatrix.api.JobMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ymatrix.api.JobMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ymatrix.api.JobMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ymatrix.api.JobMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ymatrix.api.JobMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.ymatrix.api.JobMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ymatrix.api.JobMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.ymatrix.api.JobMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.ymatrix.api.JobMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.JobMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.JobMetadata)
      cn.ymatrix.api.JobMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ymatrix.api.MxGateService.internal_static_api_JobMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ymatrix.api.MxGateService.internal_static_api_JobMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ymatrix.api.JobMetadata.class, cn.ymatrix.api.JobMetadata.Builder.class);
    }

    // Construct using cn.ymatrix.api.JobMetadata.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getColumnsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      schema_ = "";

      table_ = "";

      projection_ = "";

      insertProjection_ = "";

      selectProjection_ = "";

      uniqueKeyClause_ = "";

      delimiter_ = "";

      if (columnsBuilder_ == null) {
        columns_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        columnsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.ymatrix.api.MxGateService.internal_static_api_JobMetadata_descriptor;
    }

    @java.lang.Override
    public cn.ymatrix.api.JobMetadata getDefaultInstanceForType() {
      return cn.ymatrix.api.JobMetadata.getDefaultInstance();
    }

    @java.lang.Override
    public cn.ymatrix.api.JobMetadata build() {
      cn.ymatrix.api.JobMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.ymatrix.api.JobMetadata buildPartial() {
      cn.ymatrix.api.JobMetadata result = new cn.ymatrix.api.JobMetadata(this);
      int from_bitField0_ = bitField0_;
      result.schema_ = schema_;
      result.table_ = table_;
      result.projection_ = projection_;
      result.insertProjection_ = insertProjection_;
      result.selectProjection_ = selectProjection_;
      result.uniqueKeyClause_ = uniqueKeyClause_;
      result.delimiter_ = delimiter_;
      if (columnsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          columns_ = java.util.Collections.unmodifiableList(columns_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.columns_ = columns_;
      } else {
        result.columns_ = columnsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.ymatrix.api.JobMetadata) {
        return mergeFrom((cn.ymatrix.api.JobMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.ymatrix.api.JobMetadata other) {
      if (other == cn.ymatrix.api.JobMetadata.getDefaultInstance()) return this;
      if (!other.getSchema().isEmpty()) {
        schema_ = other.schema_;
        onChanged();
      }
      if (!other.getTable().isEmpty()) {
        table_ = other.table_;
        onChanged();
      }
      if (!other.getProjection().isEmpty()) {
        projection_ = other.projection_;
        onChanged();
      }
      if (!other.getInsertProjection().isEmpty()) {
        insertProjection_ = other.insertProjection_;
        onChanged();
      }
      if (!other.getSelectProjection().isEmpty()) {
        selectProjection_ = other.selectProjection_;
        onChanged();
      }
      if (!other.getUniqueKeyClause().isEmpty()) {
        uniqueKeyClause_ = other.uniqueKeyClause_;
        onChanged();
      }
      if (!other.getDelimiter().isEmpty()) {
        delimiter_ = other.delimiter_;
        onChanged();
      }
      if (columnsBuilder_ == null) {
        if (!other.columns_.isEmpty()) {
          if (columns_.isEmpty()) {
            columns_ = other.columns_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureColumnsIsMutable();
            columns_.addAll(other.columns_);
          }
          onChanged();
        }
      } else {
        if (!other.columns_.isEmpty()) {
          if (columnsBuilder_.isEmpty()) {
            columnsBuilder_.dispose();
            columnsBuilder_ = null;
            columns_ = other.columns_;
            bitField0_ = (bitField0_ & ~0x00000001);
            columnsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getColumnsFieldBuilder() : null;
          } else {
            columnsBuilder_.addAllMessages(other.columns_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.ymatrix.api.JobMetadata parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.ymatrix.api.JobMetadata) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object schema_ = "";
    /**
     * <code>string schema = 1;</code>
     * @return The schema.
     */
    public java.lang.String getSchema() {
      java.lang.Object ref = schema_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schema_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string schema = 1;</code>
     * @return The bytes for schema.
     */
    public com.google.protobuf.ByteString
        getSchemaBytes() {
      java.lang.Object ref = schema_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schema_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string schema = 1;</code>
     * @param value The schema to set.
     * @return This builder for chaining.
     */
    public Builder setSchema(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      schema_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string schema = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSchema() {
      
      schema_ = getDefaultInstance().getSchema();
      onChanged();
      return this;
    }
    /**
     * <code>string schema = 1;</code>
     * @param value The bytes for schema to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      schema_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object table_ = "";
    /**
     * <code>string table = 2;</code>
     * @return The table.
     */
    public java.lang.String getTable() {
      java.lang.Object ref = table_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        table_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string table = 2;</code>
     * @return The bytes for table.
     */
    public com.google.protobuf.ByteString
        getTableBytes() {
      java.lang.Object ref = table_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        table_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string table = 2;</code>
     * @param value The table to set.
     * @return This builder for chaining.
     */
    public Builder setTable(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      table_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string table = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTable() {
      
      table_ = getDefaultInstance().getTable();
      onChanged();
      return this;
    }
    /**
     * <code>string table = 2;</code>
     * @param value The bytes for table to set.
     * @return This builder for chaining.
     */
    public Builder setTableBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      table_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object projection_ = "";
    /**
     * <code>string projection = 3;</code>
     * @return The projection.
     */
    public java.lang.String getProjection() {
      java.lang.Object ref = projection_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        projection_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string projection = 3;</code>
     * @return The bytes for projection.
     */
    public com.google.protobuf.ByteString
        getProjectionBytes() {
      java.lang.Object ref = projection_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projection_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string projection = 3;</code>
     * @param value The projection to set.
     * @return This builder for chaining.
     */
    public Builder setProjection(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      projection_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string projection = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProjection() {
      
      projection_ = getDefaultInstance().getProjection();
      onChanged();
      return this;
    }
    /**
     * <code>string projection = 3;</code>
     * @param value The bytes for projection to set.
     * @return This builder for chaining.
     */
    public Builder setProjectionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      projection_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object insertProjection_ = "";
    /**
     * <code>string insert_projection = 4;</code>
     * @return The insertProjection.
     */
    public java.lang.String getInsertProjection() {
      java.lang.Object ref = insertProjection_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        insertProjection_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string insert_projection = 4;</code>
     * @return The bytes for insertProjection.
     */
    public com.google.protobuf.ByteString
        getInsertProjectionBytes() {
      java.lang.Object ref = insertProjection_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        insertProjection_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string insert_projection = 4;</code>
     * @param value The insertProjection to set.
     * @return This builder for chaining.
     */
    public Builder setInsertProjection(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      insertProjection_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string insert_projection = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearInsertProjection() {
      
      insertProjection_ = getDefaultInstance().getInsertProjection();
      onChanged();
      return this;
    }
    /**
     * <code>string insert_projection = 4;</code>
     * @param value The bytes for insertProjection to set.
     * @return This builder for chaining.
     */
    public Builder setInsertProjectionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      insertProjection_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object selectProjection_ = "";
    /**
     * <code>string select_projection = 5;</code>
     * @return The selectProjection.
     */
    public java.lang.String getSelectProjection() {
      java.lang.Object ref = selectProjection_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        selectProjection_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string select_projection = 5;</code>
     * @return The bytes for selectProjection.
     */
    public com.google.protobuf.ByteString
        getSelectProjectionBytes() {
      java.lang.Object ref = selectProjection_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        selectProjection_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string select_projection = 5;</code>
     * @param value The selectProjection to set.
     * @return This builder for chaining.
     */
    public Builder setSelectProjection(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      selectProjection_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string select_projection = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSelectProjection() {
      
      selectProjection_ = getDefaultInstance().getSelectProjection();
      onChanged();
      return this;
    }
    /**
     * <code>string select_projection = 5;</code>
     * @param value The bytes for selectProjection to set.
     * @return This builder for chaining.
     */
    public Builder setSelectProjectionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      selectProjection_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object uniqueKeyClause_ = "";
    /**
     * <code>string unique_key_clause = 6;</code>
     * @return The uniqueKeyClause.
     */
    public java.lang.String getUniqueKeyClause() {
      java.lang.Object ref = uniqueKeyClause_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uniqueKeyClause_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string unique_key_clause = 6;</code>
     * @return The bytes for uniqueKeyClause.
     */
    public com.google.protobuf.ByteString
        getUniqueKeyClauseBytes() {
      java.lang.Object ref = uniqueKeyClause_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uniqueKeyClause_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string unique_key_clause = 6;</code>
     * @param value The uniqueKeyClause to set.
     * @return This builder for chaining.
     */
    public Builder setUniqueKeyClause(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uniqueKeyClause_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string unique_key_clause = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUniqueKeyClause() {
      
      uniqueKeyClause_ = getDefaultInstance().getUniqueKeyClause();
      onChanged();
      return this;
    }
    /**
     * <code>string unique_key_clause = 6;</code>
     * @param value The bytes for uniqueKeyClause to set.
     * @return This builder for chaining.
     */
    public Builder setUniqueKeyClauseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uniqueKeyClause_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object delimiter_ = "";
    /**
     * <code>string delimiter = 7;</code>
     * @return The delimiter.
     */
    public java.lang.String getDelimiter() {
      java.lang.Object ref = delimiter_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        delimiter_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string delimiter = 7;</code>
     * @return The bytes for delimiter.
     */
    public com.google.protobuf.ByteString
        getDelimiterBytes() {
      java.lang.Object ref = delimiter_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        delimiter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string delimiter = 7;</code>
     * @param value The delimiter to set.
     * @return This builder for chaining.
     */
    public Builder setDelimiter(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      delimiter_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string delimiter = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDelimiter() {
      
      delimiter_ = getDefaultInstance().getDelimiter();
      onChanged();
      return this;
    }
    /**
     * <code>string delimiter = 7;</code>
     * @param value The bytes for delimiter to set.
     * @return This builder for chaining.
     */
    public Builder setDelimiterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      delimiter_ = value;
      onChanged();
      return this;
    }

    private java.util.List<cn.ymatrix.api.ColumnMeta> columns_ =
      java.util.Collections.emptyList();
    private void ensureColumnsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        columns_ = new java.util.ArrayList<cn.ymatrix.api.ColumnMeta>(columns_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.ymatrix.api.ColumnMeta, cn.ymatrix.api.ColumnMeta.Builder, cn.ymatrix.api.ColumnMetaOrBuilder> columnsBuilder_;

    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public java.util.List<cn.ymatrix.api.ColumnMeta> getColumnsList() {
      if (columnsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(columns_);
      } else {
        return columnsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public int getColumnsCount() {
      if (columnsBuilder_ == null) {
        return columns_.size();
      } else {
        return columnsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public cn.ymatrix.api.ColumnMeta getColumns(int index) {
      if (columnsBuilder_ == null) {
        return columns_.get(index);
      } else {
        return columnsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public Builder setColumns(
        int index, cn.ymatrix.api.ColumnMeta value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.set(index, value);
        onChanged();
      } else {
        columnsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public Builder setColumns(
        int index, cn.ymatrix.api.ColumnMeta.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.set(index, builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public Builder addColumns(cn.ymatrix.api.ColumnMeta value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.add(value);
        onChanged();
      } else {
        columnsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public Builder addColumns(
        int index, cn.ymatrix.api.ColumnMeta value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.add(index, value);
        onChanged();
      } else {
        columnsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public Builder addColumns(
        cn.ymatrix.api.ColumnMeta.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.add(builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public Builder addColumns(
        int index, cn.ymatrix.api.ColumnMeta.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.add(index, builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public Builder addAllColumns(
        java.lang.Iterable<? extends cn.ymatrix.api.ColumnMeta> values) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, columns_);
        onChanged();
      } else {
        columnsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public Builder clearColumns() {
      if (columnsBuilder_ == null) {
        columns_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        columnsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public Builder removeColumns(int index) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.remove(index);
        onChanged();
      } else {
        columnsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public cn.ymatrix.api.ColumnMeta.Builder getColumnsBuilder(
        int index) {
      return getColumnsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public cn.ymatrix.api.ColumnMetaOrBuilder getColumnsOrBuilder(
        int index) {
      if (columnsBuilder_ == null) {
        return columns_.get(index);  } else {
        return columnsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public java.util.List<? extends cn.ymatrix.api.ColumnMetaOrBuilder> 
         getColumnsOrBuilderList() {
      if (columnsBuilder_ != null) {
        return columnsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(columns_);
      }
    }
    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public cn.ymatrix.api.ColumnMeta.Builder addColumnsBuilder() {
      return getColumnsFieldBuilder().addBuilder(
          cn.ymatrix.api.ColumnMeta.getDefaultInstance());
    }
    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public cn.ymatrix.api.ColumnMeta.Builder addColumnsBuilder(
        int index) {
      return getColumnsFieldBuilder().addBuilder(
          index, cn.ymatrix.api.ColumnMeta.getDefaultInstance());
    }
    /**
     * <code>repeated .api.ColumnMeta columns = 8;</code>
     */
    public java.util.List<cn.ymatrix.api.ColumnMeta.Builder> 
         getColumnsBuilderList() {
      return getColumnsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.ymatrix.api.ColumnMeta, cn.ymatrix.api.ColumnMeta.Builder, cn.ymatrix.api.ColumnMetaOrBuilder> 
        getColumnsFieldBuilder() {
      if (columnsBuilder_ == null) {
        columnsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cn.ymatrix.api.ColumnMeta, cn.ymatrix.api.ColumnMeta.Builder, cn.ymatrix.api.ColumnMetaOrBuilder>(
                columns_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        columns_ = null;
      }
      return columnsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.JobMetadata)
  }

  // @@protoc_insertion_point(class_scope:api.JobMetadata)
  private static final cn.ymatrix.api.JobMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.ymatrix.api.JobMetadata();
  }

  public static cn.ymatrix.api.JobMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JobMetadata>
      PARSER = new com.google.protobuf.AbstractParser<JobMetadata>() {
    @java.lang.Override
    public JobMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JobMetadata(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JobMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JobMetadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.ymatrix.api.JobMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

