// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mxgate_service.proto

package cn.ymatrix.api;

public final class MxGateService {
  private MxGateService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_GetJobMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_GetJobMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_GetJobMetadata_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_GetJobMetadata_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_GetJobMetadata_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_GetJobMetadata_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_JobMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_JobMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_ColumnMeta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_ColumnMeta_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_SendData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_SendData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_SendData_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_SendData_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_SendData_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_SendData_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_SendData_Response_ErrorLinesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_SendData_Response_ErrorLinesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024mxgate_service.proto\022\003api\"\205\001\n\016GetJobMe" +
      "tadata\032(\n\007Request\022\016\n\006schema\030\001 \001(\t\022\r\n\005tab" +
      "le\030\002 \001(\t\032I\n\010Response\022\014\n\004code\030\001 \001(\005\022\013\n\003ms" +
      "g\030\002 \001(\t\022\"\n\010metadata\030\003 \001(\0132\020.api.JobMetad" +
      "ata\"\306\001\n\013JobMetadata\022\016\n\006schema\030\001 \001(\t\022\r\n\005t" +
      "able\030\002 \001(\t\022\022\n\nprojection\030\003 \001(\t\022\031\n\021insert" +
      "_projection\030\004 \001(\t\022\031\n\021select_projection\030\005" +
      " \001(\t\022\031\n\021unique_key_clause\030\006 \001(\t\022\021\n\tdelim" +
      "iter\030\007 \001(\t\022 \n\007columns\030\010 \003(\0132\017.api.Column" +
      "Meta\"\316\001\n\nColumnMeta\022\014\n\004type\030\001 \001(\t\022\014\n\004nam" +
      "e\030\002 \001(\t\022\013\n\003num\030\003 \001(\005\022\023\n\013is_not_null\030\004 \001(" +
      "\010\022\026\n\016is_set_default\030\005 \001(\010\022\017\n\007default\030\006 \001" +
      "(\t\022\021\n\tis_serial\030\007 \001(\010\022\023\n\013is_excluded\030\010 \001" +
      "(\010\022\025\n\ris_upsert_key\030\t \001(\010\022\032\n\022is_deduplic" +
      "ate_key\030\n \001(\010\"\357\001\n\010SendData\0326\n\007Request\022\016\n" +
      "\006schema\030\001 \001(\t\022\r\n\005table\030\002 \001(\t\022\014\n\004data\030\003 \001" +
      "(\t\032\252\001\n\010Response\022\014\n\004code\030\001 \001(\005\022\013\n\003msg\030\002 \001" +
      "(\t\022\023\n\013tuple_count\030\003 \001(\003\022;\n\013error_lines\030\004" +
      " \003(\0132&.api.SendData.Response.ErrorLinesE" +
      "ntry\0321\n\017ErrorLinesEntry\022\013\n\003key\030\001 \001(\003\022\r\n\005" +
      "value\030\002 \001(\t:\0028\0012\220\001\n\006MXGate\022K\n\016GetJobMeta" +
      "data\022\033.api.GetJobMetadata.Request\032\034.api." +
      "GetJobMetadata.Response\0229\n\010SendData\022\025.ap" +
      "i.SendData.Request\032\026.api.SendData.Respon" +
      "seB\'\n\016cn.ymatrix.apiB\rMxGateServiceP\001\242\002\003" +
      "MXSb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_api_GetJobMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_GetJobMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_GetJobMetadata_descriptor,
        new java.lang.String[] { });
    internal_static_api_GetJobMetadata_Request_descriptor =
      internal_static_api_GetJobMetadata_descriptor.getNestedTypes().get(0);
    internal_static_api_GetJobMetadata_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_GetJobMetadata_Request_descriptor,
        new java.lang.String[] { "Schema", "Table", });
    internal_static_api_GetJobMetadata_Response_descriptor =
      internal_static_api_GetJobMetadata_descriptor.getNestedTypes().get(1);
    internal_static_api_GetJobMetadata_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_GetJobMetadata_Response_descriptor,
        new java.lang.String[] { "Code", "Msg", "Metadata", });
    internal_static_api_JobMetadata_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_JobMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_JobMetadata_descriptor,
        new java.lang.String[] { "Schema", "Table", "Projection", "InsertProjection", "SelectProjection", "UniqueKeyClause", "Delimiter", "Columns", });
    internal_static_api_ColumnMeta_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_api_ColumnMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_ColumnMeta_descriptor,
        new java.lang.String[] { "Type", "Name", "Num", "IsNotNull", "IsSetDefault", "Default", "IsSerial", "IsExcluded", "IsUpsertKey", "IsDeduplicateKey", });
    internal_static_api_SendData_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_api_SendData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_SendData_descriptor,
        new java.lang.String[] { });
    internal_static_api_SendData_Request_descriptor =
      internal_static_api_SendData_descriptor.getNestedTypes().get(0);
    internal_static_api_SendData_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_SendData_Request_descriptor,
        new java.lang.String[] { "Schema", "Table", "Data", });
    internal_static_api_SendData_Response_descriptor =
      internal_static_api_SendData_descriptor.getNestedTypes().get(1);
    internal_static_api_SendData_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_SendData_Response_descriptor,
        new java.lang.String[] { "Code", "Msg", "TupleCount", "ErrorLines", });
    internal_static_api_SendData_Response_ErrorLinesEntry_descriptor =
      internal_static_api_SendData_Response_descriptor.getNestedTypes().get(0);
    internal_static_api_SendData_Response_ErrorLinesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_SendData_Response_ErrorLinesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
