// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mxgate_service.proto

package cn.ymatrix.api;

public interface SendDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.SendData)
    com.google.protobuf.MessageOrBuilder {
}
