// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/gate/mxgate.proto

package api.matrix.mxgate;

public final class Mxgate {
  private Mxgate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetMxGateStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mxgate.GetMxGateStatus)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * Get MxGate Status
   * </pre>
   *
   * Protobuf type {@code mxgate.GetMxGateStatus}
   */
  public static final class GetMxGateStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mxgate.GetMxGateStatus)
      GetMxGateStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetMxGateStatus.newBuilder() to construct.
    private GetMxGateStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetMxGateStatus() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetMxGateStatus();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetMxGateStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return api.matrix.mxgate.Mxgate.internal_static_mxgate_GetMxGateStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return api.matrix.mxgate.Mxgate.internal_static_mxgate_GetMxGateStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              api.matrix.mxgate.Mxgate.GetMxGateStatus.class, api.matrix.mxgate.Mxgate.GetMxGateStatus.Builder.class);
    }

    public interface ResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:mxgate.GetMxGateStatus.Response)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      int getCode();

      /**
       * <code>string msg = 2;</code>
       * @return The msg.
       */
      java.lang.String getMsg();
      /**
       * <code>string msg = 2;</code>
       * @return The bytes for msg.
       */
      com.google.protobuf.ByteString
          getMsgBytes();

      /**
       * <code>.mxgate.MxGateStatus status = 3;</code>
       * @return Whether the status field is set.
       */
      boolean hasStatus();
      /**
       * <code>.mxgate.MxGateStatus status = 3;</code>
       * @return The status.
       */
      api.matrix.mxgate.Mxgate.MxGateStatus getStatus();
      /**
       * <code>.mxgate.MxGateStatus status = 3;</code>
       */
      api.matrix.mxgate.Mxgate.MxGateStatusOrBuilder getStatusOrBuilder();
    }
    /**
     * Protobuf type {@code mxgate.GetMxGateStatus.Response}
     */
    public static final class Response extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:mxgate.GetMxGateStatus.Response)
        ResponseOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Response.newBuilder() to construct.
      private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Response() {
        msg_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Response();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Response(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                code_ = input.readInt32();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                msg_ = s;
                break;
              }
              case 26: {
                api.matrix.mxgate.Mxgate.MxGateStatus.Builder subBuilder = null;
                if (status_ != null) {
                  subBuilder = status_.toBuilder();
                }
                status_ = input.readMessage(api.matrix.mxgate.Mxgate.MxGateStatus.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(status_);
                  status_ = subBuilder.buildPartial();
                }

                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return api.matrix.mxgate.Mxgate.internal_static_mxgate_GetMxGateStatus_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return api.matrix.mxgate.Mxgate.internal_static_mxgate_GetMxGateStatus_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                api.matrix.mxgate.Mxgate.GetMxGateStatus.Response.class, api.matrix.mxgate.Mxgate.GetMxGateStatus.Response.Builder.class);
      }

      public static final int CODE_FIELD_NUMBER = 1;
      private int code_;
      /**
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }

      public static final int MSG_FIELD_NUMBER = 2;
      private volatile java.lang.Object msg_;
      /**
       * <code>string msg = 2;</code>
       * @return The msg.
       */
      @java.lang.Override
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @return The bytes for msg.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int STATUS_FIELD_NUMBER = 3;
      private api.matrix.mxgate.Mxgate.MxGateStatus status_;
      /**
       * <code>.mxgate.MxGateStatus status = 3;</code>
       * @return Whether the status field is set.
       */
      @java.lang.Override
      public boolean hasStatus() {
        return status_ != null;
      }
      /**
       * <code>.mxgate.MxGateStatus status = 3;</code>
       * @return The status.
       */
      @java.lang.Override
      public api.matrix.mxgate.Mxgate.MxGateStatus getStatus() {
        return status_ == null ? api.matrix.mxgate.Mxgate.MxGateStatus.getDefaultInstance() : status_;
      }
      /**
       * <code>.mxgate.MxGateStatus status = 3;</code>
       */
      @java.lang.Override
      public api.matrix.mxgate.Mxgate.MxGateStatusOrBuilder getStatusOrBuilder() {
        return getStatus();
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (code_ != 0) {
          output.writeInt32(1, code_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
        }
        if (status_ != null) {
          output.writeMessage(3, getStatus());
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (code_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, code_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
        }
        if (status_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, getStatus());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof api.matrix.mxgate.Mxgate.GetMxGateStatus.Response)) {
          return super.equals(obj);
        }
        api.matrix.mxgate.Mxgate.GetMxGateStatus.Response other = (api.matrix.mxgate.Mxgate.GetMxGateStatus.Response) obj;

        if (getCode()
            != other.getCode()) return false;
        if (!getMsg()
            .equals(other.getMsg())) return false;
        if (hasStatus() != other.hasStatus()) return false;
        if (hasStatus()) {
          if (!getStatus()
              .equals(other.getStatus())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
        if (hasStatus()) {
          hash = (37 * hash) + STATUS_FIELD_NUMBER;
          hash = (53 * hash) + getStatus().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static api.matrix.mxgate.Mxgate.GetMxGateStatus.Response parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static api.matrix.mxgate.Mxgate.GetMxGateStatus.Response parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static api.matrix.mxgate.Mxgate.GetMxGateStatus.Response parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static api.matrix.mxgate.Mxgate.GetMxGateStatus.Response parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static api.matrix.mxgate.Mxgate.GetMxGateStatus.Response parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static api.matrix.mxgate.Mxgate.GetMxGateStatus.Response parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static api.matrix.mxgate.Mxgate.GetMxGateStatus.Response parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static api.matrix.mxgate.Mxgate.GetMxGateStatus.Response parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static api.matrix.mxgate.Mxgate.GetMxGateStatus.Response parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static api.matrix.mxgate.Mxgate.GetMxGateStatus.Response parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static api.matrix.mxgate.Mxgate.GetMxGateStatus.Response parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static api.matrix.mxgate.Mxgate.GetMxGateStatus.Response parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(api.matrix.mxgate.Mxgate.GetMxGateStatus.Response prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code mxgate.GetMxGateStatus.Response}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:mxgate.GetMxGateStatus.Response)
          api.matrix.mxgate.Mxgate.GetMxGateStatus.ResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return api.matrix.mxgate.Mxgate.internal_static_mxgate_GetMxGateStatus_Response_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return api.matrix.mxgate.Mxgate.internal_static_mxgate_GetMxGateStatus_Response_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  api.matrix.mxgate.Mxgate.GetMxGateStatus.Response.class, api.matrix.mxgate.Mxgate.GetMxGateStatus.Response.Builder.class);
        }

        // Construct using api.matrix.mxgate.Mxgate.GetMxGateStatus.Response.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          code_ = 0;

          msg_ = "";

          if (statusBuilder_ == null) {
            status_ = null;
          } else {
            status_ = null;
            statusBuilder_ = null;
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return api.matrix.mxgate.Mxgate.internal_static_mxgate_GetMxGateStatus_Response_descriptor;
        }

        @java.lang.Override
        public api.matrix.mxgate.Mxgate.GetMxGateStatus.Response getDefaultInstanceForType() {
          return api.matrix.mxgate.Mxgate.GetMxGateStatus.Response.getDefaultInstance();
        }

        @java.lang.Override
        public api.matrix.mxgate.Mxgate.GetMxGateStatus.Response build() {
          api.matrix.mxgate.Mxgate.GetMxGateStatus.Response result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public api.matrix.mxgate.Mxgate.GetMxGateStatus.Response buildPartial() {
          api.matrix.mxgate.Mxgate.GetMxGateStatus.Response result = new api.matrix.mxgate.Mxgate.GetMxGateStatus.Response(this);
          result.code_ = code_;
          result.msg_ = msg_;
          if (statusBuilder_ == null) {
            result.status_ = status_;
          } else {
            result.status_ = statusBuilder_.build();
          }
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof api.matrix.mxgate.Mxgate.GetMxGateStatus.Response) {
            return mergeFrom((api.matrix.mxgate.Mxgate.GetMxGateStatus.Response)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(api.matrix.mxgate.Mxgate.GetMxGateStatus.Response other) {
          if (other == api.matrix.mxgate.Mxgate.GetMxGateStatus.Response.getDefaultInstance()) return this;
          if (other.getCode() != 0) {
            setCode(other.getCode());
          }
          if (!other.getMsg().isEmpty()) {
            msg_ = other.msg_;
            onChanged();
          }
          if (other.hasStatus()) {
            mergeStatus(other.getStatus());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          api.matrix.mxgate.Mxgate.GetMxGateStatus.Response parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (api.matrix.mxgate.Mxgate.GetMxGateStatus.Response) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int code_ ;
        /**
         * <code>int32 code = 1;</code>
         * @return The code.
         */
        @java.lang.Override
        public int getCode() {
          return code_;
        }
        /**
         * <code>int32 code = 1;</code>
         * @param value The code to set.
         * @return This builder for chaining.
         */
        public Builder setCode(int value) {
          
          code_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 code = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearCode() {
          
          code_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object msg_ = "";
        /**
         * <code>string msg = 2;</code>
         * @return The msg.
         */
        public java.lang.String getMsg() {
          java.lang.Object ref = msg_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            msg_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string msg = 2;</code>
         * @return The bytes for msg.
         */
        public com.google.protobuf.ByteString
            getMsgBytes() {
          java.lang.Object ref = msg_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            msg_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string msg = 2;</code>
         * @param value The msg to set.
         * @return This builder for chaining.
         */
        public Builder setMsg(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          msg_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string msg = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearMsg() {
          
          msg_ = getDefaultInstance().getMsg();
          onChanged();
          return this;
        }
        /**
         * <code>string msg = 2;</code>
         * @param value The bytes for msg to set.
         * @return This builder for chaining.
         */
        public Builder setMsgBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          msg_ = value;
          onChanged();
          return this;
        }

        private api.matrix.mxgate.Mxgate.MxGateStatus status_;
        private com.google.protobuf.SingleFieldBuilderV3<
            api.matrix.mxgate.Mxgate.MxGateStatus, api.matrix.mxgate.Mxgate.MxGateStatus.Builder, api.matrix.mxgate.Mxgate.MxGateStatusOrBuilder> statusBuilder_;
        /**
         * <code>.mxgate.MxGateStatus status = 3;</code>
         * @return Whether the status field is set.
         */
        public boolean hasStatus() {
          return statusBuilder_ != null || status_ != null;
        }
        /**
         * <code>.mxgate.MxGateStatus status = 3;</code>
         * @return The status.
         */
        public api.matrix.mxgate.Mxgate.MxGateStatus getStatus() {
          if (statusBuilder_ == null) {
            return status_ == null ? api.matrix.mxgate.Mxgate.MxGateStatus.getDefaultInstance() : status_;
          } else {
            return statusBuilder_.getMessage();
          }
        }
        /**
         * <code>.mxgate.MxGateStatus status = 3;</code>
         */
        public Builder setStatus(api.matrix.mxgate.Mxgate.MxGateStatus value) {
          if (statusBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            status_ = value;
            onChanged();
          } else {
            statusBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.mxgate.MxGateStatus status = 3;</code>
         */
        public Builder setStatus(
            api.matrix.mxgate.Mxgate.MxGateStatus.Builder builderForValue) {
          if (statusBuilder_ == null) {
            status_ = builderForValue.build();
            onChanged();
          } else {
            statusBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.mxgate.MxGateStatus status = 3;</code>
         */
        public Builder mergeStatus(api.matrix.mxgate.Mxgate.MxGateStatus value) {
          if (statusBuilder_ == null) {
            if (status_ != null) {
              status_ =
                api.matrix.mxgate.Mxgate.MxGateStatus.newBuilder(status_).mergeFrom(value).buildPartial();
            } else {
              status_ = value;
            }
            onChanged();
          } else {
            statusBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.mxgate.MxGateStatus status = 3;</code>
         */
        public Builder clearStatus() {
          if (statusBuilder_ == null) {
            status_ = null;
            onChanged();
          } else {
            status_ = null;
            statusBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.mxgate.MxGateStatus status = 3;</code>
         */
        public api.matrix.mxgate.Mxgate.MxGateStatus.Builder getStatusBuilder() {
          
          onChanged();
          return getStatusFieldBuilder().getBuilder();
        }
        /**
         * <code>.mxgate.MxGateStatus status = 3;</code>
         */
        public api.matrix.mxgate.Mxgate.MxGateStatusOrBuilder getStatusOrBuilder() {
          if (statusBuilder_ != null) {
            return statusBuilder_.getMessageOrBuilder();
          } else {
            return status_ == null ?
                api.matrix.mxgate.Mxgate.MxGateStatus.getDefaultInstance() : status_;
          }
        }
        /**
         * <code>.mxgate.MxGateStatus status = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            api.matrix.mxgate.Mxgate.MxGateStatus, api.matrix.mxgate.Mxgate.MxGateStatus.Builder, api.matrix.mxgate.Mxgate.MxGateStatusOrBuilder> 
            getStatusFieldBuilder() {
          if (statusBuilder_ == null) {
            statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                api.matrix.mxgate.Mxgate.MxGateStatus, api.matrix.mxgate.Mxgate.MxGateStatus.Builder, api.matrix.mxgate.Mxgate.MxGateStatusOrBuilder>(
                    getStatus(),
                    getParentForChildren(),
                    isClean());
            status_ = null;
          }
          return statusBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:mxgate.GetMxGateStatus.Response)
      }

      // @@protoc_insertion_point(class_scope:mxgate.GetMxGateStatus.Response)
      private static final api.matrix.mxgate.Mxgate.GetMxGateStatus.Response DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new api.matrix.mxgate.Mxgate.GetMxGateStatus.Response();
      }

      public static api.matrix.mxgate.Mxgate.GetMxGateStatus.Response getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Response>
          PARSER = new com.google.protobuf.AbstractParser<Response>() {
        @java.lang.Override
        public Response parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Response(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Response> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Response> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public api.matrix.mxgate.Mxgate.GetMxGateStatus.Response getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof api.matrix.mxgate.Mxgate.GetMxGateStatus)) {
        return super.equals(obj);
      }
      api.matrix.mxgate.Mxgate.GetMxGateStatus other = (api.matrix.mxgate.Mxgate.GetMxGateStatus) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static api.matrix.mxgate.Mxgate.GetMxGateStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static api.matrix.mxgate.Mxgate.GetMxGateStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static api.matrix.mxgate.Mxgate.GetMxGateStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static api.matrix.mxgate.Mxgate.GetMxGateStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static api.matrix.mxgate.Mxgate.GetMxGateStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static api.matrix.mxgate.Mxgate.GetMxGateStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static api.matrix.mxgate.Mxgate.GetMxGateStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static api.matrix.mxgate.Mxgate.GetMxGateStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static api.matrix.mxgate.Mxgate.GetMxGateStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static api.matrix.mxgate.Mxgate.GetMxGateStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static api.matrix.mxgate.Mxgate.GetMxGateStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static api.matrix.mxgate.Mxgate.GetMxGateStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(api.matrix.mxgate.Mxgate.GetMxGateStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Get MxGate Status
     * </pre>
     *
     * Protobuf type {@code mxgate.GetMxGateStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mxgate.GetMxGateStatus)
        api.matrix.mxgate.Mxgate.GetMxGateStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return api.matrix.mxgate.Mxgate.internal_static_mxgate_GetMxGateStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return api.matrix.mxgate.Mxgate.internal_static_mxgate_GetMxGateStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                api.matrix.mxgate.Mxgate.GetMxGateStatus.class, api.matrix.mxgate.Mxgate.GetMxGateStatus.Builder.class);
      }

      // Construct using api.matrix.mxgate.Mxgate.GetMxGateStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return api.matrix.mxgate.Mxgate.internal_static_mxgate_GetMxGateStatus_descriptor;
      }

      @java.lang.Override
      public api.matrix.mxgate.Mxgate.GetMxGateStatus getDefaultInstanceForType() {
        return api.matrix.mxgate.Mxgate.GetMxGateStatus.getDefaultInstance();
      }

      @java.lang.Override
      public api.matrix.mxgate.Mxgate.GetMxGateStatus build() {
        api.matrix.mxgate.Mxgate.GetMxGateStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public api.matrix.mxgate.Mxgate.GetMxGateStatus buildPartial() {
        api.matrix.mxgate.Mxgate.GetMxGateStatus result = new api.matrix.mxgate.Mxgate.GetMxGateStatus(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof api.matrix.mxgate.Mxgate.GetMxGateStatus) {
          return mergeFrom((api.matrix.mxgate.Mxgate.GetMxGateStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(api.matrix.mxgate.Mxgate.GetMxGateStatus other) {
        if (other == api.matrix.mxgate.Mxgate.GetMxGateStatus.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        api.matrix.mxgate.Mxgate.GetMxGateStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (api.matrix.mxgate.Mxgate.GetMxGateStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mxgate.GetMxGateStatus)
    }

    // @@protoc_insertion_point(class_scope:mxgate.GetMxGateStatus)
    private static final api.matrix.mxgate.Mxgate.GetMxGateStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new api.matrix.mxgate.Mxgate.GetMxGateStatus();
    }

    public static api.matrix.mxgate.Mxgate.GetMxGateStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetMxGateStatus>
        PARSER = new com.google.protobuf.AbstractParser<GetMxGateStatus>() {
      @java.lang.Override
      public GetMxGateStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetMxGateStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetMxGateStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetMxGateStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public api.matrix.mxgate.Mxgate.GetMxGateStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MxGateStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mxgate.MxGateStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 pid = 1;</code>
     * @return The pid.
     */
    int getPid();

    /**
     * <code>string launch_at = 2;</code>
     * @return The launchAt.
     */
    java.lang.String getLaunchAt();
    /**
     * <code>string launch_at = 2;</code>
     * @return The bytes for launchAt.
     */
    com.google.protobuf.ByteString
        getLaunchAtBytes();

    /**
     * <code>int64 up_for = 3;</code>
     * @return The upFor.
     */
    long getUpFor();

    /**
     * <code>string binary_path = 4;</code>
     * @return The binaryPath.
     */
    java.lang.String getBinaryPath();
    /**
     * <code>string binary_path = 4;</code>
     * @return The bytes for binaryPath.
     */
    com.google.protobuf.ByteString
        getBinaryPathBytes();

    /**
     * <code>string log_path = 5;</code>
     * @return The logPath.
     */
    java.lang.String getLogPath();
    /**
     * <code>string log_path = 5;</code>
     * @return The bytes for logPath.
     */
    com.google.protobuf.ByteString
        getLogPathBytes();

    /**
     * <code>string config_path = 6;</code>
     * @return The configPath.
     */
    java.lang.String getConfigPath();
    /**
     * <code>string config_path = 6;</code>
     * @return The bytes for configPath.
     */
    com.google.protobuf.ByteString
        getConfigPathBytes();
  }
  /**
   * Protobuf type {@code mxgate.MxGateStatus}
   */
  public static final class MxGateStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mxgate.MxGateStatus)
      MxGateStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MxGateStatus.newBuilder() to construct.
    private MxGateStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MxGateStatus() {
      launchAt_ = "";
      binaryPath_ = "";
      logPath_ = "";
      configPath_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MxGateStatus();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MxGateStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              pid_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              launchAt_ = s;
              break;
            }
            case 24: {

              upFor_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              binaryPath_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              logPath_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              configPath_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return api.matrix.mxgate.Mxgate.internal_static_mxgate_MxGateStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return api.matrix.mxgate.Mxgate.internal_static_mxgate_MxGateStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              api.matrix.mxgate.Mxgate.MxGateStatus.class, api.matrix.mxgate.Mxgate.MxGateStatus.Builder.class);
    }

    public static final int PID_FIELD_NUMBER = 1;
    private int pid_;
    /**
     * <code>int32 pid = 1;</code>
     * @return The pid.
     */
    @java.lang.Override
    public int getPid() {
      return pid_;
    }

    public static final int LAUNCH_AT_FIELD_NUMBER = 2;
    private volatile java.lang.Object launchAt_;
    /**
     * <code>string launch_at = 2;</code>
     * @return The launchAt.
     */
    @java.lang.Override
    public java.lang.String getLaunchAt() {
      java.lang.Object ref = launchAt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        launchAt_ = s;
        return s;
      }
    }
    /**
     * <code>string launch_at = 2;</code>
     * @return The bytes for launchAt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLaunchAtBytes() {
      java.lang.Object ref = launchAt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        launchAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UP_FOR_FIELD_NUMBER = 3;
    private long upFor_;
    /**
     * <code>int64 up_for = 3;</code>
     * @return The upFor.
     */
    @java.lang.Override
    public long getUpFor() {
      return upFor_;
    }

    public static final int BINARY_PATH_FIELD_NUMBER = 4;
    private volatile java.lang.Object binaryPath_;
    /**
     * <code>string binary_path = 4;</code>
     * @return The binaryPath.
     */
    @java.lang.Override
    public java.lang.String getBinaryPath() {
      java.lang.Object ref = binaryPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        binaryPath_ = s;
        return s;
      }
    }
    /**
     * <code>string binary_path = 4;</code>
     * @return The bytes for binaryPath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBinaryPathBytes() {
      java.lang.Object ref = binaryPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        binaryPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOG_PATH_FIELD_NUMBER = 5;
    private volatile java.lang.Object logPath_;
    /**
     * <code>string log_path = 5;</code>
     * @return The logPath.
     */
    @java.lang.Override
    public java.lang.String getLogPath() {
      java.lang.Object ref = logPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logPath_ = s;
        return s;
      }
    }
    /**
     * <code>string log_path = 5;</code>
     * @return The bytes for logPath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLogPathBytes() {
      java.lang.Object ref = logPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONFIG_PATH_FIELD_NUMBER = 6;
    private volatile java.lang.Object configPath_;
    /**
     * <code>string config_path = 6;</code>
     * @return The configPath.
     */
    @java.lang.Override
    public java.lang.String getConfigPath() {
      java.lang.Object ref = configPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        configPath_ = s;
        return s;
      }
    }
    /**
     * <code>string config_path = 6;</code>
     * @return The bytes for configPath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConfigPathBytes() {
      java.lang.Object ref = configPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        configPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pid_ != 0) {
        output.writeInt32(1, pid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(launchAt_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, launchAt_);
      }
      if (upFor_ != 0L) {
        output.writeInt64(3, upFor_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(binaryPath_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, binaryPath_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(logPath_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, logPath_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(configPath_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, configPath_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(launchAt_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, launchAt_);
      }
      if (upFor_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, upFor_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(binaryPath_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, binaryPath_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(logPath_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, logPath_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(configPath_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, configPath_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof api.matrix.mxgate.Mxgate.MxGateStatus)) {
        return super.equals(obj);
      }
      api.matrix.mxgate.Mxgate.MxGateStatus other = (api.matrix.mxgate.Mxgate.MxGateStatus) obj;

      if (getPid()
          != other.getPid()) return false;
      if (!getLaunchAt()
          .equals(other.getLaunchAt())) return false;
      if (getUpFor()
          != other.getUpFor()) return false;
      if (!getBinaryPath()
          .equals(other.getBinaryPath())) return false;
      if (!getLogPath()
          .equals(other.getLogPath())) return false;
      if (!getConfigPath()
          .equals(other.getConfigPath())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PID_FIELD_NUMBER;
      hash = (53 * hash) + getPid();
      hash = (37 * hash) + LAUNCH_AT_FIELD_NUMBER;
      hash = (53 * hash) + getLaunchAt().hashCode();
      hash = (37 * hash) + UP_FOR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpFor());
      hash = (37 * hash) + BINARY_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getBinaryPath().hashCode();
      hash = (37 * hash) + LOG_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getLogPath().hashCode();
      hash = (37 * hash) + CONFIG_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getConfigPath().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static api.matrix.mxgate.Mxgate.MxGateStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static api.matrix.mxgate.Mxgate.MxGateStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static api.matrix.mxgate.Mxgate.MxGateStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static api.matrix.mxgate.Mxgate.MxGateStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static api.matrix.mxgate.Mxgate.MxGateStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static api.matrix.mxgate.Mxgate.MxGateStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static api.matrix.mxgate.Mxgate.MxGateStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static api.matrix.mxgate.Mxgate.MxGateStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static api.matrix.mxgate.Mxgate.MxGateStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static api.matrix.mxgate.Mxgate.MxGateStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static api.matrix.mxgate.Mxgate.MxGateStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static api.matrix.mxgate.Mxgate.MxGateStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(api.matrix.mxgate.Mxgate.MxGateStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mxgate.MxGateStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mxgate.MxGateStatus)
        api.matrix.mxgate.Mxgate.MxGateStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return api.matrix.mxgate.Mxgate.internal_static_mxgate_MxGateStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return api.matrix.mxgate.Mxgate.internal_static_mxgate_MxGateStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                api.matrix.mxgate.Mxgate.MxGateStatus.class, api.matrix.mxgate.Mxgate.MxGateStatus.Builder.class);
      }

      // Construct using api.matrix.mxgate.Mxgate.MxGateStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pid_ = 0;

        launchAt_ = "";

        upFor_ = 0L;

        binaryPath_ = "";

        logPath_ = "";

        configPath_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return api.matrix.mxgate.Mxgate.internal_static_mxgate_MxGateStatus_descriptor;
      }

      @java.lang.Override
      public api.matrix.mxgate.Mxgate.MxGateStatus getDefaultInstanceForType() {
        return api.matrix.mxgate.Mxgate.MxGateStatus.getDefaultInstance();
      }

      @java.lang.Override
      public api.matrix.mxgate.Mxgate.MxGateStatus build() {
        api.matrix.mxgate.Mxgate.MxGateStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public api.matrix.mxgate.Mxgate.MxGateStatus buildPartial() {
        api.matrix.mxgate.Mxgate.MxGateStatus result = new api.matrix.mxgate.Mxgate.MxGateStatus(this);
        result.pid_ = pid_;
        result.launchAt_ = launchAt_;
        result.upFor_ = upFor_;
        result.binaryPath_ = binaryPath_;
        result.logPath_ = logPath_;
        result.configPath_ = configPath_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof api.matrix.mxgate.Mxgate.MxGateStatus) {
          return mergeFrom((api.matrix.mxgate.Mxgate.MxGateStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(api.matrix.mxgate.Mxgate.MxGateStatus other) {
        if (other == api.matrix.mxgate.Mxgate.MxGateStatus.getDefaultInstance()) return this;
        if (other.getPid() != 0) {
          setPid(other.getPid());
        }
        if (!other.getLaunchAt().isEmpty()) {
          launchAt_ = other.launchAt_;
          onChanged();
        }
        if (other.getUpFor() != 0L) {
          setUpFor(other.getUpFor());
        }
        if (!other.getBinaryPath().isEmpty()) {
          binaryPath_ = other.binaryPath_;
          onChanged();
        }
        if (!other.getLogPath().isEmpty()) {
          logPath_ = other.logPath_;
          onChanged();
        }
        if (!other.getConfigPath().isEmpty()) {
          configPath_ = other.configPath_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        api.matrix.mxgate.Mxgate.MxGateStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (api.matrix.mxgate.Mxgate.MxGateStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int pid_ ;
      /**
       * <code>int32 pid = 1;</code>
       * @return The pid.
       */
      @java.lang.Override
      public int getPid() {
        return pid_;
      }
      /**
       * <code>int32 pid = 1;</code>
       * @param value The pid to set.
       * @return This builder for chaining.
       */
      public Builder setPid(int value) {
        
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPid() {
        
        pid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object launchAt_ = "";
      /**
       * <code>string launch_at = 2;</code>
       * @return The launchAt.
       */
      public java.lang.String getLaunchAt() {
        java.lang.Object ref = launchAt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          launchAt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string launch_at = 2;</code>
       * @return The bytes for launchAt.
       */
      public com.google.protobuf.ByteString
          getLaunchAtBytes() {
        java.lang.Object ref = launchAt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          launchAt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string launch_at = 2;</code>
       * @param value The launchAt to set.
       * @return This builder for chaining.
       */
      public Builder setLaunchAt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        launchAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string launch_at = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLaunchAt() {
        
        launchAt_ = getDefaultInstance().getLaunchAt();
        onChanged();
        return this;
      }
      /**
       * <code>string launch_at = 2;</code>
       * @param value The bytes for launchAt to set.
       * @return This builder for chaining.
       */
      public Builder setLaunchAtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        launchAt_ = value;
        onChanged();
        return this;
      }

      private long upFor_ ;
      /**
       * <code>int64 up_for = 3;</code>
       * @return The upFor.
       */
      @java.lang.Override
      public long getUpFor() {
        return upFor_;
      }
      /**
       * <code>int64 up_for = 3;</code>
       * @param value The upFor to set.
       * @return This builder for chaining.
       */
      public Builder setUpFor(long value) {
        
        upFor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 up_for = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUpFor() {
        
        upFor_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object binaryPath_ = "";
      /**
       * <code>string binary_path = 4;</code>
       * @return The binaryPath.
       */
      public java.lang.String getBinaryPath() {
        java.lang.Object ref = binaryPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          binaryPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string binary_path = 4;</code>
       * @return The bytes for binaryPath.
       */
      public com.google.protobuf.ByteString
          getBinaryPathBytes() {
        java.lang.Object ref = binaryPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          binaryPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string binary_path = 4;</code>
       * @param value The binaryPath to set.
       * @return This builder for chaining.
       */
      public Builder setBinaryPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        binaryPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string binary_path = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBinaryPath() {
        
        binaryPath_ = getDefaultInstance().getBinaryPath();
        onChanged();
        return this;
      }
      /**
       * <code>string binary_path = 4;</code>
       * @param value The bytes for binaryPath to set.
       * @return This builder for chaining.
       */
      public Builder setBinaryPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        binaryPath_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object logPath_ = "";
      /**
       * <code>string log_path = 5;</code>
       * @return The logPath.
       */
      public java.lang.String getLogPath() {
        java.lang.Object ref = logPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          logPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string log_path = 5;</code>
       * @return The bytes for logPath.
       */
      public com.google.protobuf.ByteString
          getLogPathBytes() {
        java.lang.Object ref = logPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string log_path = 5;</code>
       * @param value The logPath to set.
       * @return This builder for chaining.
       */
      public Builder setLogPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        logPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string log_path = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogPath() {
        
        logPath_ = getDefaultInstance().getLogPath();
        onChanged();
        return this;
      }
      /**
       * <code>string log_path = 5;</code>
       * @param value The bytes for logPath to set.
       * @return This builder for chaining.
       */
      public Builder setLogPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        logPath_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object configPath_ = "";
      /**
       * <code>string config_path = 6;</code>
       * @return The configPath.
       */
      public java.lang.String getConfigPath() {
        java.lang.Object ref = configPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          configPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string config_path = 6;</code>
       * @return The bytes for configPath.
       */
      public com.google.protobuf.ByteString
          getConfigPathBytes() {
        java.lang.Object ref = configPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          configPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string config_path = 6;</code>
       * @param value The configPath to set.
       * @return This builder for chaining.
       */
      public Builder setConfigPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        configPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string config_path = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearConfigPath() {
        
        configPath_ = getDefaultInstance().getConfigPath();
        onChanged();
        return this;
      }
      /**
       * <code>string config_path = 6;</code>
       * @param value The bytes for configPath to set.
       * @return This builder for chaining.
       */
      public Builder setConfigPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        configPath_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mxgate.MxGateStatus)
    }

    // @@protoc_insertion_point(class_scope:mxgate.MxGateStatus)
    private static final api.matrix.mxgate.Mxgate.MxGateStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new api.matrix.mxgate.Mxgate.MxGateStatus();
    }

    public static api.matrix.mxgate.Mxgate.MxGateStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MxGateStatus>
        PARSER = new com.google.protobuf.AbstractParser<MxGateStatus>() {
      @java.lang.Override
      public MxGateStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MxGateStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MxGateStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MxGateStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public api.matrix.mxgate.Mxgate.MxGateStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mxgate_GetMxGateStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mxgate_GetMxGateStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mxgate_GetMxGateStatus_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mxgate_GetMxGateStatus_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mxgate_MxGateStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mxgate_MxGateStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025api/gate/mxgate.proto\022\006mxgate\032\033google/" +
      "protobuf/empty.proto\"^\n\017GetMxGateStatus\032" +
      "K\n\010Response\022\014\n\004code\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022$" +
      "\n\006status\030\003 \001(\0132\024.mxgate.MxGateStatus\"z\n\014" +
      "MxGateStatus\022\013\n\003pid\030\001 \001(\005\022\021\n\tlaunch_at\030\002" +
      " \001(\t\022\016\n\006up_for\030\003 \001(\003\022\023\n\013binary_path\030\004 \001(" +
      "\t\022\020\n\010log_path\030\005 \001(\t\022\023\n\013config_path\030\006 \001(\t" +
      "B\023\n\021api.matrix.mxgateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_mxgate_GetMxGateStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mxgate_GetMxGateStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mxgate_GetMxGateStatus_descriptor,
        new java.lang.String[] { });
    internal_static_mxgate_GetMxGateStatus_Response_descriptor =
      internal_static_mxgate_GetMxGateStatus_descriptor.getNestedTypes().get(0);
    internal_static_mxgate_GetMxGateStatus_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mxgate_GetMxGateStatus_Response_descriptor,
        new java.lang.String[] { "Code", "Msg", "Status", });
    internal_static_mxgate_MxGateStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mxgate_MxGateStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mxgate_MxGateStatus_descriptor,
        new java.lang.String[] { "Pid", "LaunchAt", "UpFor", "BinaryPath", "LogPath", "ConfigPath", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
