name: pr_pipeline

on:
  pull_request:
    branches: [ master ]

jobs:

  check_changes:
    runs-on: ubuntu-20.04
    steps:
      # https://github.com/marketplace/actions/pull-request-title-rules
      - uses: dbhao/action-pr-title@master
        id: wipcheck
        with:
          disallowed_prefixes: 'wip,rfc,do-not-merge,skipci,skip-ci,skip_ci,ciskip,ci-skip,ci_skip' # title should not start with the given prefix
          prefix_case_sensitive: false # title prefix are case insensitive
      - name: cancel_wip
        if: steps.wipcheck.outputs.matched == 'true'
        uses: andymckay/cancel-action@0.2

  build_and_test:
    needs: [ check_changes ]
    runs-on: ubuntu-20.04
    steps:
      - name: Granting private modules access
        run: |
          git config --global url."https://${{secrets.CI_USER}}:${{secrets.PAT}}@github.com/ymatrix-data".insteadOf "https://github.com/ymatrix-data"

      - uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '18'

      - name: Test
        run: mvn clean test
#        run: mvn clean test -Dtest="TestHttpTask#TestSendDataBlockingWithCircuitBreakerOnBySlowCall"

      - name: Build
        run: mvn clean -Dmaven.test.skip compile package
